# Generated by Django 3.1.3 on 2020-12-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
