# Generated by Django 3.1.4 on 2020-12-22 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201222_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
